<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Naumans-Air.home" failures="1" tests="9" name="Personal Loan" time="0.058" errors="0" timestamp="07 Oct 2019 20:23:41 GMT">
  <testcase classname="Test.DemoTestClass" name="test3" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.DemoTestClass.test3(DemoTestClass.java:38)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="Test.DemoTestClass4" name="CarLoanAPILogin" time="0.002"/>
  <testcase classname="Test.DemoTestClass4" name="CarLoanWebLogin" time="0.001"/>
  <testcase classname="Test.DemoTestClass4" name="MobileCarLoanLogin1" time="0.001"/>
  <testcase classname="Test.DemoTestClass4" name="MobileCarLoanLogin2" time="0.004"/>
  <testcase classname="Test.DemoTestClass4" name="MobileCarLoanLogin3" time="0.001"/>
  <testcase classname="Test.DemoTestClass4" name="MobileCarLoanLogin4" time="0.002"/>
  <testcase classname="Test.DemoTestClass4" name="MobileCarLoanLogin5" time="0.001"/>
  <testcase classname="Test.DemotestClass2" name="test4" time="0.002"/>
  <testcase classname="Test.DemoTestClass" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="Test.DemoTestClass" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Personal Loan -->
